version: '3'
services:
  myapp:
    build:
      context: /execution
      dockerfile: Dockerfile
    volumes:
      - /execution/:/opt/execution/
      - /execution/adds/:/opt/execution/adds
    ports:
      - 8000:8000
    depends_on:
      - selenium
  selenium:
    image: selenium/standalone-chrome:94.0
    ports:
      - 4444:4444
    networks:
      - mynetwork
  db:
    image: postgres:latest
    environment:
      - PGHOST=host.docker.internal
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=salma
      - POSTGRES_DB=guernida
      - PGPORT=5433
    ports:
      - 5433:5432
    networks:
      - mynetwork
  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge